server:
 port: 8080

spring:
  datasource:
    username: mydb
    password: dSHZKqbktVxIDil
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        jdbc:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
    - url: https://nopaper.ru/
      name: Nopaper
    - url: https://www.svetlovka.ru/
      name: Светловка
#    - url: https://krasnodar.ru/
#      name: krasnodar
#    - url: https://novo-sibirsk.ru/
#      name: novosibirsk
#    - url: http://playback.ru/
#      name: playback
#    - url: https://skillbox.ru/
#      name: skillbox
#    - url: https://corian-yug.ru/
#      name: corian-yug
#    - url: https://ipfran.ru/
#      name: ipfran
#    - url: https://volochek.life/
#      name: volochek
#    - url: https://4pda.to/
#      name: 4pda
#    - url: https://dombulgakova.ru/
#      name: dombulgakova