server:
 port: 8080

spring:
  datasource:
    username: mydb
    password: dSHZKqbktVxIDil
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

indexing-settings:
  sites:
    - url: https://playback.ru/
      name: playback.ru