server:
 port: 8080

spring:
  datasource:
    username: mydb
    password: dSHZKqbktVxIDil
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

indexing-settings:
  sites:
#    - url: https://www.tretyakovgallery.ru/
#      name: tretyakovgallery
    - url: https://www.svetlovka.ru/
      name: svetlovka
#    - url: https://krasnodar.ru/
#      name: krasnodar
#    - url: https://novo-sibirsk.ru/
#      name: novosibirsk
#    - url: https://www.playback.ru/
#      name: playback
#    - url: https://skillbox.ru/
#      name: skillbox
#    - url: https://corian-yug.ru/
#      name: corian-yug
#    - url: https://ipfran.ru/
#      name: ipfran
#    - url: https://volochek.life/
#      name: volochek
    - url: https://nopaper.ru
      name: nopaper